### ISSUE TITLE
Question: Is it reasonably possible to support the embedded-storage-async traits?

### ISSUE THREAD

**Issue by flyaruu** [esp-rs/esp-storage#40]
I'm looking into using a storage crate (https://crates.io/crates/sequential-storage/1.0.0) with Embassy, but it depends on the embedded-storage-async traits.

Are there plans to support those in esp-storage?

**Comment by bjoernQ** [comment]
Unfortunately, we cannot really support something which is really async because the ROM functions used are not async. Even if they were there is still the problem that the flash needs to be detached while performing operations on it

But it seems others had success by using an async wrapper of the blocking operations: https://github.com/esp-rs/esp-storage/issues/39#issuecomment-1980991446

It's certainly still blocking but if it's okay in that situation to block other async tasks during the (relatively short running) operations you might can get away with that.

We could provide that functionality (the async wrapper over blocking behavior) directly here but that feels wrong and might fool users

**Comment by flyaruu** [comment]
Ah ok, I figured looking at the rom functions, but I thought I ask anyway. I'll give it a shot. Thanks for getting back to me.
